services:
  goal_gen:
    image: goal_gen:latest
    container_name: goal_gen
    command:
      ["bash", "./goal_gen/train_ip2p.sh", "./goal_gen/config/train.json"]
    volumes:
      - ./resources:/app/resources
      - ./results:/app/results
      - ./data:/app/data
